//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : ChangePasswordForm.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.struts.form;


public class ChangePasswordForm extends ITSZForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3277812757265513711L;
	/**
	 * 
	 */
	private String loginId;
	private String oldPassword;
	private String newPassword1;
	private String newPassword;
	
	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getOldPassword() {
		return oldPassword;
	}
	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}
	public String getNewPassword1() {
		return newPassword1;
	}
	public void setNewPassword1(String newPassword1) {
		this.newPassword1 = newPassword1;
	}
	public String getNewPassword() {
		return newPassword;
	}
	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}
}
