//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : EnquiryPositionForm.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.struts.form;


public class EnquiryPositionForm extends ITSZForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = -3245864837098966067L;
	private String accountId;
	private String instrCode;
	private int fromIdx;

	public String getAccountId() {
		return accountId;
	}
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}
	public int getFromIdx() {
		return fromIdx;
	}
	public void setFromIdx(int fromIdx) {
		this.fromIdx = fromIdx;
	}
	public String getInstrCode() {
		return instrCode;
	}
	public void setInstrCode(String instrCode) {
		this.instrCode = instrCode;
	}

}
