//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : EnquireRTQForm.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.struts.form;


public class EnquireRTQForm extends ITSZForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 241893578022434542L;
	private String instrCode;

	public String getInstrCode() {
		return instrCode;
	}
	public void setInstrCode(String instrCode) {
		this.instrCode = instrCode;
	}
}
