//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : EnquireAccountForm.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.struts.form;


public class EnquireAccountForm extends ITSZForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7831831953865940915L;
	private String accountId;

	public String getAccountId() {
		return accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}
}
