//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : TransactionProtectionForm.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.struts.form;


public class TransactionProtectionForm extends ITSZForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = -1863650162509728069L;
	private String loginId;
	private String password;
	private String transactionProtection;
	private String lang;

	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getTransactionProtection() {
		return transactionProtection;
	}
	public void setTransactionProtection(String transactionProtection) {
		this.transactionProtection = transactionProtection;
	}
	public String getLang() {
		return lang;
	}
	public void setLang(String lang) {
		this.lang = lang;
	}
}
