/***************************************************************************
                          kdevview.h  -  description
                             -------------------
    begin                : ËÄ 09 21 05:30:27 CST 2000
    copyright            : (C) 2000 by 
    email                : 
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef KDEVVIEW_H
#define KDEVVIEW_H

// include files for Qt
#include <qwidget.h>

class KdevDoc;

/**
 * This class provides an incomplete base for your application view.
 * 	
 * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
 * @version KDevelop version 1.1 code generation
 */
class KdevView : public QWidget
{
  Q_OBJECT

  friend KdevDoc;

  public:
    /** Constructor for the view
    	* @param pDoc  your document instance that the view represents. Create a document before calling the constructor
    	* or connect an already existing document to a new MDI child widget.*/
    KdevView(KdevDoc* pDoc, QWidget* parent, const char *name, int wflags);
    /** Destructor for the main view */
    ~KdevView();
		/** returns a pointer to the document connected to the view*/
    KdevDoc *getDocument() const;
    /** gets called to redraw the document contents if it has been modified */
		void update(KdevView* pSender);
    /** contains the implementation for printing functionality and gets called by KdevApp::slotFilePrint() */
    void print(QPrinter *pPrinter);
		
  protected:
	  virtual void closeEvent(QCloseEvent*);

	  KdevDoc *doc;
	
  private:
	
};

#endif
