<?xml version = "1.0"?>

<!-- Fig. 23.25: displayBook.xsl                        -->
<!-- XSLT style sheet that transforms XML generated by  -->
<!-- displayBook.py into XHTML Basic.                   -->

<xsl:stylesheet version = "1.0"
   xmlns:xsl = "http://www.w3.org/1999/XSL/Transform">

   <xsl:output method = "xml" omit-xml-declaration = "no" 
      indent = "yes" doctype-system =
      "http://www.w3.org/TR/xhtml-basic/xhtml-basic10.dtd"
      doctype-public = "-//W3C//DTD XHTML Basic 1.0//EN"/>

<!-- specify the root of the XML document -->
<!-- that references this style sheet     -->
<xsl:template match = "product">

   <html xmlns = "http://www.w3.org/1999/xhtml">
   
      <head>

         <!-- obtain book title from script to place in title -->
         <title><xsl:value-of select = "title" /></title>

         <link rel = "stylesheet" href = "/bookstore/styles.css" 
            type = "text/css" />
      </head>

      <body>
         <p class = "bigFont">
            <xsl:value-of select = "title" /></p>

         <img src = "/bookstore/small_images/{imageFile}"
            alt = "{title}" />

         <!-- show price, ISBN, edition and copyright -->
         <p class = "bold">Price:
            <xsl:value-of select = "price" /></p>

         <p class = "bold">ISBN:
            <xsl:value-of select = "isbn" /></p>

         <p class = "bold">Edition:
            <xsl:value-of select = "editionNumber" /></p>

         <p class = "bold">Copyright:
            <xsl:value-of select = "copyright" /></p>

         <!-- create Add to Cart button -->
         <p>
            <form method = "post" action = "addToCart.py?ID=%s">
               <p><input type = "submit" 
                     value = "Add to Cart" /></p>
            </form>
         </p>

         <!-- create View Cart button -->
         <p>
            <form method = "post" action = "viewCart.py?ID=%s">
               <p><input type = "submit" 
                     value = "View Cart" /></p>
            </form>
         </p>

      </body>

   </html> 

</xsl:template>

<!--
 ***************************************************************
 * (C) Copyright 2002 by Deitel & Associates, Inc. and         *
 * Prentice Hall. All Rights Reserved.                         *
 *                                                             *
 * DISCLAIMER: The authors and publisher of this book have     *
 * used their best efforts in preparing the book. These        *
 * efforts include the development, research, and testing of   *
 * the theories and programs to determine their effectiveness. *
 * The authors and publisher make no warranty of any kind,     *
 * expressed or implied, with regard to these programs or to   *
 * the documentation contained in these books. The authors     *
 * and publisher shall not be liable in any event for          *
 * incidental or consequential damages in connection with, or  *
 * arising out of, the furnishing, performance, or use of      *
 * these programs.                                             *
 ***************************************************************
-->

</xsl:stylesheet>
