//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : ChangePwdResponseModel.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.common.model.response;

import com.itsz.sht.common.model.AbstractResponseModel;
import com.taifook.mcs.core.beans.msg.ChangePasswordResponse;


public class ChangePwdResponseModel extends AbstractResponseModel {
	private String loginId;
	private String changePasswordStatus;
	private ChangePasswordResponse changePasswordResponse;
	

	/**
	 * @return the changePasswordResponse
	 */
	public ChangePasswordResponse getChangePasswordResponse() {
		return changePasswordResponse;
	}
	/**
	 * @param changePasswordResponse the changePasswordResponse to set
	 */
	public void setChangePasswordResponse(
			ChangePasswordResponse changePasswordResponse) {
		this.changePasswordResponse = changePasswordResponse;
	}
	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getChangePasswordStatus() {
		return changePasswordStatus;
	}
	public void setChangePasswordStatus(String changePasswordStatus) {
		this.changePasswordStatus = changePasswordStatus;
	}
}
