//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : TransactionProtectionResponseModel.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.common.model.response;

import com.itsz.sht.common.model.AbstractResponseModel;
import com.taifook.mcs.core.beans.msg.TransactionProtectionResponse;


public class TransactionProtectionResponseModel  extends AbstractResponseModel{
	private String loginId;
	private String transactionProtectionStatus;
	private String needVarifyPassword;
	private TransactionProtectionResponse transactionProtectionRes;
	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getTransactionProtectionStatus() {
		return transactionProtectionStatus;
	}
	public void setTransactionProtectionStatus(String transactionProtectionStatus) {
		this.transactionProtectionStatus = transactionProtectionStatus;
	}
	public String getNeedVarifyPassword() {
		return needVarifyPassword;
	}
	public void setNeedVarifyPassword(String needVarifyPassword) {
		this.needVarifyPassword = needVarifyPassword;
	}
	public TransactionProtectionResponse getTransactionProtectionRes() {
		return transactionProtectionRes;
	}
	public void setTransactionProtectionRes(
			TransactionProtectionResponse transactionProtectionRes) {
		this.transactionProtectionRes = transactionProtectionRes;
	}
}
