//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : AccountSummaryAction.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.itsz.sht.common.DataModelUtil;
import com.itsz.sht.common.model.request.EnquireAccountRequestModel;
import com.itsz.sht.common.model.response.EnquireAccountResponseModel;
import com.itsz.sht.struts.form.AccountSummaryForm;
import com.itsz.sht.vp.ViewProvider;
import com.itsz.sht.vp.common.ProcessBean;


public class AccountSummaryAction extends ITSZAction {
	public ActionForward executeAction(ViewProvider vp,
			ActionMapping mapping,
			ActionForm form,
			HttpServletRequest request,
			HttpServletResponse response) {
		EnquireAccountRequestModel model = new EnquireAccountRequestModel();
		DataModelUtil.form2Model(request,(AccountSummaryForm) form, model, response);
		EnquireAccountResponseModel responseModel = facade.enquireAccountDetail(model);
		ProcessBean processBean = new ProcessBean(responseModel, null, mapping, request, response);
		return vp.processAccountSummary(processBean);
	}
}
