//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderDetailAction.java
//  @ Date : 2007-5-21
//  @ Author : 
//
//



package com.itsz.sht.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.itsz.sht.common.Constants;
import com.itsz.sht.common.Consts;
import com.itsz.sht.common.DataModelUtil;
import com.itsz.sht.common.model.request.OrderDetailRequestModel;
import com.itsz.sht.common.model.response.listorder.OrderDetailTradeResponseModel;
import com.itsz.sht.common.user.UserObject;
import com.itsz.sht.struts.form.OrderDetailForm;
import com.itsz.sht.vp.ViewProvider;
import com.itsz.sht.vp.common.ProcessBean;

/**
 * $Id: ModifyDetailAction.java,v 1.2 2010/12/21 11:33:43 zxfan Exp $
 * @Project:portal.head
 * @File:OrderDetailAction.java
 * @Description:
 * @Author:Cimenon Saint
 * @Date:2007-5-21
 */
public class ModifyDetailAction extends ITSZAction {
	
	/**
	 * 
	 * @Author:Cimenon Saint
	 * @Time:16:26:49
	 * @param vp
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward executeAction(ViewProvider vp,
									ActionMapping mapping,
									ActionForm form,
									HttpServletRequest request,
									HttpServletResponse response) {
		OrderDetailRequestModel model = new OrderDetailRequestModel();
		DataModelUtil.form2Model(request, (OrderDetailForm) form, model, response);
		UserObject user = (UserObject) request.getSession().getAttribute(Constants.USER);
		if (user != null && user.getTradeInfoObject() != null)
			model.setAccountId(user.getTradeInfoObject().getTradingAccount());
		
		OrderDetailTradeResponseModel responseModel = facade.orderDetail(model);
		if (Consts.Global.Status.NORMAL.equals(responseModel.getReturnCode())) {
			setTokenToSession(request);
		}
		ProcessBean processBean = new ProcessBean(responseModel,null, mapping, request,response);
		return vp.processModifyDetail(processBean);
	}
}
