/* Generated by Together */

package com.itsz.sht.common.auto;

public class AutoPurchaseConstants {
    public static final String LOCAL_JNDI_AUTOPURCHASE = "local/AutoPurchase";
    public static class PurchaseStatus{
        public static final String ST_SUCCESS = "SUCCESS";
        public static final String ST_OFFLINE = "OFFLINE-ACCOUNT";
        public static final String ST_NOT_ENOUGH_MONEY = "NOT-ENOUGH-MONEY";
        public static final String ST_ACCOUNT_CLOSED = "ACCOUNT-CLOSED";
        public static final String ST_SYS_ERROR = "SYS-ERROR";
        public static final String ST_QRY_ALL = "ALL STATUS" ;
    }

}
