package com.redsaga.hibernatesample.step4.dao;

import com.redsaga.hibernatesample.step4.base.BaseVoteOptionDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the vote_option table.
 * Any customizations belong here.
 */
public class VoteOptionDAO extends BaseVoteOptionDAO {
}