<?xml version="1.0" encoding="UTF-8"?><definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://server.ws.cb.sun.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://server.ws.cb.sun.com/" name="SupplierService">
<types>
<xsd:schema>
<xsd:import namespace="http://server.ws.cb.sun.com/" schemaLocation="http://localhost:8080/jaxws-coffee-supplier/SupplierService?xsd=1"></xsd:import>
</xsd:schema>
</types>
<message name="placeOrder">
<part name="parameters" element="tns:placeOrder"></part>
</message>
<message name="placeOrderResponse">
<part name="parameters" element="tns:placeOrderResponse"></part>
</message>
<message name="getPriceList">
<part name="parameters" element="tns:getPriceList"></part>
</message>
<message name="getPriceListResponse">
<part name="parameters" element="tns:getPriceListResponse"></part>
</message>
<portType name="Supplier">
<operation name="placeOrder">
<input message="tns:placeOrder"></input>
<output message="tns:placeOrderResponse"></output>
</operation>
<operation name="getPriceList">
<input message="tns:getPriceList"></input>
<output message="tns:getPriceListResponse"></output>
</operation>
</portType>
<binding name="SupplierPortBinding" type="tns:Supplier">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"></soap:binding>
<operation name="placeOrder">
<soap:operation soapAction=""></soap:operation>
<input>
<soap:body use="literal"></soap:body>
</input>
<output>
<soap:body use="literal"></soap:body>
</output>
</operation>
<operation name="getPriceList">
<soap:operation soapAction=""></soap:operation>
<input>
<soap:body use="literal"></soap:body>
</input>
<output>
<soap:body use="literal"></soap:body>
</output>
</operation>
</binding>
<service name="SupplierService">
<port name="SupplierPort" binding="tns:SupplierPortBinding">
<soap:address location="http://localhost:8080/jaxws-coffee-supplier/SupplierService"></soap:address>
</port>
</service>
</definitions>