-- Delete the tutorial database tables
ALTER TABLE EJB_ORDER_PART DROP CONSTRAINT FK_1;
ALTER TABLE EJB_ORDER_VENDOR_PART DROP CONSTRAINT FK_2;
ALTER TABLE EJB_ORDER_VENDOR_PART DROP CONSTRAINT FK_3;
ALTER TABLE EJB_ORDER_LINEITEM DROP CONSTRAINT FK_4;
ALTER TABLE EJB_ORDER_LINEITEM DROP CONSTRAINT FK_5;

ALTER TABLE BANK_TX DROP CONSTRAINT fk_tx_account_id;
ALTER TABLE BANK_CUSTOMER_ACCOUNT_XREF DROP CONSTRAINT fk_bank_customer_id;
ALTER TABLE BANK_CUSTOMER_ACCOUNT_XREF DROP CONSTRAINT fk_bank_account_id;
ALTER TABLE BANK_ACCOUNT DROP CONSTRAINT pk_account;
ALTER TABLE BANK_CUSTOMER DROP CONSTRAINT pk_customer;
ALTER TABLE BANK_TX DROP CONSTRAINT pk_tx;

DROP TABLE WEB_BOOKSTORE_BOOKS;

DROP TABLE EJB_ORDER_LINEITEM;
DROP TABLE EJB_ORDER_ORDER;
DROP TABLE EJB_ORDER_VENDOR_PART;
DROP TABLE EJB_ORDER_VENDOR;
DROP TABLE EJB_ORDER_PART_DETAIL;
DROP TABLE EJB_ORDER_PART;
DROP TABLE EJB_ORDER_SEQUENCE_GENERATOR;

DROP TABLE BANK_SEQUENCE_GENERATOR;
DROP TABLE BANK_CUSTOMER_ACCOUNT_XREF;
DROP TABLE BANK_TX;
DROP TABLE BANK_CUSTOMER;
DROP TABLE BANK_ACCOUNT;
