package org.crazyit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.8
 * Mon May 24 22:37:39 CST 2010
 * Generated source version: 2.2.8
 * 
 */
 
@WebService(targetNamespace = "http://www.crazyit.org", name = "person")
@XmlSeeAlso({ObjectFactory.class,org.crazyit.blog.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Person {

    @WebResult(name = "sayHelloResponse", targetNamespace = "http://www.crazyit.org", partName = "parameters")
    @WebMethod(action = "http://www.crazyit.org/greet")
    public SayHelloResponse sayHello(
        @WebParam(partName = "parameters", name = "sayHello", targetNamespace = "http://www.crazyit.org")
        SayHello parameters
    );
}
