
/*
 * 
 */

package org.crazyit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.8
 * Mon May 24 22:37:39 CST 2010
 * Generated source version: 2.2.8
 * 
 */


@WebServiceClient(name = "personWS", 
                  wsdlLocation = "http://192.168.1.88:7001/PersonServiceBean/personWS?WSDL",
                  targetNamespace = "http://www.crazyit.org") 
public class PersonWS extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.crazyit.org", "personWS");
    public final static QName PersonPort = new QName("http://www.crazyit.org", "personPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.88:7001/PersonServiceBean/personWS?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://192.168.1.88:7001/PersonServiceBean/personWS?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PersonWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns Person
     */
    @WebEndpoint(name = "personPort")
    public Person getPersonPort() {
        return super.getPort(PersonPort, Person.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Person
     */
    @WebEndpoint(name = "personPort")
    public Person getPersonPort(WebServiceFeature... features) {
        return super.getPort(PersonPort, Person.class, features);
    }

}
