<?xml version = "1.0"?>

<!-- Fig. 23.30: allBooks.xsl                           -->
<!-- XSLT style sheet that transforms XML generated by  -->
<!-- books.py into WML.                                 -->

<xsl:stylesheet version = "1.0"
   xmlns:xsl = "http://www.w3.org/1999/XSL/Transform">

   <xsl:output method = "xml" omit-xml-declaration = "no" 
      indent = "yes" doctype-system = 
      "http://www.wapforum.org/DTD/wml12.dtd"
      doctype-public = "-//WAPFORUM//DTD WML 1.2//EN"/>

<!-- template for catalog element -->
<xsl:template match = "catalog">

   <wml>

      <head>
         <meta forua = "true" http-equiv = "Cache-Control" 
            content = "max-age=0" />
      </head>

      <card title = "Book List">

         <p>

            <b>Available Books</b><br />
            Click a link to view book information<br />

            <!-- match product elements to product template -->
            <xsl:apply-templates select = "/catalog/product">

               <!-- sort products by title -->
               <xsl:sort select = "title" />

            </xsl:apply-templates>

         </p>

      </card>

   </wml>

</xsl:template>

<!-- template for building row of Product information -->
<xsl:template match = "product">

   <a href="displayBook.py?ID=%s&amp;isbn={isbn}">
      <xsl:value-of select = "title" />, <xsl:value-of 
         select = "editionNumber" />e
   </a><br />

</xsl:template>

<!-- 
  (C) Copyright 2002 by Deitel & Associates, Inc. and         
  Prentice Hall. All Rights Reserved.                         
                                                              
  DISCLAIMER: The authors and publisher of this book have     
  used their best efforts in preparing the book. These        
  efforts include the development, research, and testing of   
  the theories and programs to determine their effectiveness. 
  The authors and publisher make no warranty of any kind,     
  expressed or implied, with regard to these programs or to   
  the documentation contained in these books. The authors     
  and publisher shall not be liable in any event for          
  incidental or consequential damages in connection with, or  
  arising out of, the furnishing, performance, or use of      
  these programs.                                             
 -->

 </xsl:stylesheet>
