<?xml version = "1.0"?>

<!-- Fig. 23.31: displayBook.xsl                        -->
<!-- XSLT style sheet that transforms XML generated by  -->
<!-- displayBook.py into WML.                           -->

<xsl:stylesheet version = "1.0"
   xmlns:xsl = "http://www.w3.org/1999/XSL/Transform">

   <xsl:output method = "xml" omit-xml-declaration = "no" 
      indent = "yes" doctype-system = 
      "http://www.wapforum.org/DTD/wml12.dtd"
      doctype-public = "-//WAPFORUM//DTD WML 1.2//EN"/>

<!-- specify the root of the XML document -->
<!-- that references this style sheet     -->
<xsl:template match = "product">

   <wml>
      
      <head>
         <meta forua = "true" http-equiv = "Cache-Control" 
            content = "max-age=0" />
      </head>

      <!-- obtain book title from script to place in title -->   
      <card title = "{title}">

         <p>
      
            <xsl:value-of select = "title" /><br />

            <img src = "/bookstore/logo.wbmp" alt = "logo" />
            <br />

            <!-- show price, ISBN, edition and copyright -->
            Price: <xsl:value-of select = "price" /><br />
            ISBN: <xsl:value-of select = "isbn" /><br />
            Edition: <xsl:value-of select = "editionNumber" />
            <br />
            Copyright: <xsl:value-of select = "copyright" /><br />
            <br />

            <!-- add links to shopping cart -->         
            <a href = "addToCart.py?ID=%s">Add to Cart</a><br />
            <a href = "viewCart.py?ID=%s">View Cart</a><br />
         
         </p>

      </card>

   </wml>

</xsl:template>

<!--
 ***************************************************************
 * (C) Copyright 2002 by Deitel & Associates, Inc. and         *
 * Prentice Hall. All Rights Reserved.                         *
 *                                                             *
 * DISCLAIMER: The authors and publisher of this book have     *
 * used their best efforts in preparing the book. These        *
 * efforts include the development, research, and testing of   *
 * the theories and programs to determine their effectiveness. *
 * The authors and publisher make no warranty of any kind,     *
 * expressed or implied, with regard to these programs or to   *
 * the documentation contained in these books. The authors     *
 * and publisher shall not be liable in any event for          *
 * incidental or consequential damages in connection with, or  *
 * arising out of, the furnishing, performance, or use of      *
 * these programs.                                             *
 ***************************************************************
-->

</xsl:stylesheet>
