package com.redsaga.hibernatesample.step3.dao;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public abstract class _RootDAO extends com.redsaga.hibernatesample.step3.base._BaseRootDAO {
}