package com.redsaga.hibernatesample.step3.dao;

import org.apache.log4j.Logger;

import java.sql.Connection;

import net.sf.hibernate.HibernateException;
import net.sf.hibernate.Query;
import net.sf.hibernate.Session;
import net.sf.hibernate.Transaction;

import com.redsaga.hibernatesample.step3.Article;
import com.redsaga.hibernatesample.step3.base.BaseArticleDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the article table.
 * Any customizations belong here.
 */
public class ArticleDAO extends BaseArticleDAO {
	/**
	 * Logger for this class
	 */
	private static final Logger logger = Logger.getLogger(ArticleDAO.class);


}