package com.redsaga.hibernatesample.step3.dao;

import com.redsaga.hibernatesample.step3.base.BaseUserDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the user table.
 * Any customizations belong here.
 */
public class UserDAO extends BaseUserDAO {
}