//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : ChangePwdRequestModel.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.common.model.request;

import com.itsz.sht.common.model.AbstractRequestModel;


public class ChangePwdRequestModel  extends AbstractRequestModel{
	private String loginId;
	private String oldPassword;
	private String newPassword;

	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getOldPassword() {
		return oldPassword;
	}
	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}
	public String getNewPassword() {
		return newPassword;
	}
	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}
}
