//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : ChangePwdRequestModel.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.common.model.request;


import com.itsz.sht.common.model.AbstractRequestModel;

public class ProfitAndLossUpdateRequestModel  extends AbstractRequestModel{
	private String marketCode;
	private String loginID;
	private String profileID;
	private String profileInfo;

	/**
	 * @return the profileInfo
	 */
	public String getProfileInfo() {
		return profileInfo;
	}
	/**
	 * @param profileInfo the profileInfo to set
	 */
	public void setProfileInfo(String profileInfo) {
		this.profileInfo = profileInfo;
	}
	/**
	 * @return the marketCode
	 */
	public String getMarketCode() {
		return marketCode;
	}
	/**
	 * @param marketCode the marketCode to set
	 */
	public void setMarketCode(String marketCode) {
		this.marketCode = marketCode;
	}
	/**
	 * @return the loginID
	 */
	public String getLoginID() {
		return loginID;
	}
	/**
	 * @param loginID the loginID to set
	 */
	public void setLoginID(String loginID) {
		this.loginID = loginID;
	}

	/**
	 * @return the profileID
	 */
	public String getProfileID() {
		return profileID;
	}
	/**
	 * @param profileID the profileID to set
	 */
	public void setProfileID(String profileID) {
		this.profileID = profileID;
	}

	
	
}
