//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : wmt
//  @ File Name : TransactionProtectionRequestModel.java
//  @ Date : 2008-3-6
//  @ Author : kyzou
//
//



package com.itsz.sht.common.model.request;

import com.itsz.sht.common.model.AbstractRequestModel;


public class TransactionProtectionRequestModel  extends AbstractRequestModel{
	private String loginId;
	private String password;
	private String transactionProtection;
	private String needVarifyPassword;

	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getTransactionProtection() {
		return transactionProtection;
	}
	public void setTransactionProtection(String transactionProtection) {
		this.transactionProtection = transactionProtection;
	}
	public String getNeedVarifyPassword() {
		return needVarifyPassword;
	}
	public void setNeedVarifyPassword(String needVarifyPassword) {
		this.needVarifyPassword = needVarifyPassword;
	}
}
