
all: semaphore producer-consumer

producer-consumer: producer-consumer.c
	gcc -o producer-consumer producer-consumer.c

semaphore: semaphore.c
	gcc -o semaphore semaphore.c

clean:
	rm -f *.o *.bak semaphore producer-consumer

