# Generated automatically from Makefile.in by configure.
# KDE tags expanded automatically by am_edit - $Revision: 1.1 $ 
# Makefile.in generated automatically by automake 1.4a from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

####### kdevelop will overwrite this part!!! (begin)##########


SHELL = /bin/sh

srcdir = .
top_srcdir = ../../..
prefix = /usr/local
exec_prefix = ${prefix}
#>- 
bindir = ${exec_prefix}/bin
#>+ 3
DEPDIR = .deps

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/kdev
pkglibdir = $(libdir)/kdev
pkgincludedir = $(includedir)/kdev

top_builddir = ../../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
INSTALL_STRIP_FLAG =
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
AS = @AS@
AUTODIRS = 
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = @CXXCPP@
DCOPIDL = @DCOPIDL@
DCOPIDL2CPP = @DCOPIDL2CPP@
DCOP_DEPENDENCIES = @DCOP_DEPENDENCIES@
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
EXEEXT = 
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = @GMSGFMT@
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = @KDE_EXTRA_RPATH@
KDE_INCLUDES = @KDE_INCLUDES@
KDE_LDFLAGS = @KDE_LDFLAGS@
KDE_RPATH = @KDE_RPATH@
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBJPEG = @LIBJPEG@
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBSM =  -lSM
LIBSOCKET = 
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBZ = -lz
LIB_KAB = @LIB_KAB@
LIB_KDECORE = @LIB_KDECORE@
LIB_KDEUI = @LIB_KDEUI@
LIB_KFILE = @LIB_KFILE@
LIB_KFM = @LIB_KFM@
LIB_KFORMULA = @LIB_KFORMULA@
LIB_KHTML = @LIB_KHTML@
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = @LIB_KIO@
LIB_KPARTS = @LIB_KPARTS@
LIB_KSPELL = @LIB_KSPELL@
LIB_KSYCOCA = @LIB_KSYCOCA@
LIB_MEDIATOOL = @LIB_MEDIATOOL@
LIB_QT = -lqt $(LIBPNG) -lXext $(LIB_X11) $(X_PRE_LIBS)
LIB_SMB = @LIB_SMB@
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /root/qt-2.2.1/bin/moc
MSGFMT = @MSGFMT@
NOOPT_CXXFLAGS =  -fno-exceptions -fno-rtti -fno-check-new
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = kdev
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
QT_INCLUDES = -I/root/qt-2.2.1/include
QT_LDFLAGS = 
RANLIB = ranlib
REPO = -frepo
STRIP = strip
TOPSUBDIRS = @TOPSUBDIRS@
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_NLS = @USE_NLS@
USE_RTTI = -frtti
VERSION = 0.1
XGETTEXT = @XGETTEXT@
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS = 
all_includes = -I/root/qt-2.2.1/include -I/usr/X11R6/include 
all_libraries = -L/usr/X11R6/lib 
idldir = @idldir@
kde_appsdir = @kde_appsdir@
kde_bindir = @kde_bindir@
kde_cgidir = @kde_cgidir@
kde_confdir = @kde_confdir@
kde_datadir = @kde_datadir@
kde_htmldir = @kde_htmldir@
kde_icondir = @kde_icondir@
kde_includes = @kde_includes@
kde_libraries = @kde_libraries@
kde_locale = @kde_locale@
kde_mimedir = @kde_mimedir@
kde_minidir = @kde_minidir@
kde_servicesdir = @kde_servicesdir@
kde_servicetypesdir = @kde_servicetypesdir@
kde_sounddir = @kde_sounddir@
kde_toolbardir = @kde_toolbardir@
kde_wallpaperdir = @kde_wallpaperdir@
micodir = @micodir@
qt_includes = /root/qt-2.2.1/include
qt_libraries = 
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

EXTRA_DIST = index.html index-1.html index-2.html index-3.html index-4.html index-5.html index-6.html 
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../../../config.h
CONFIG_CLEAN_FILES = 
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu kdev/docs/en/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu kdev/docs/en/Makefile
	cd $(top_srcdir) && perl am_edit kdev/docs/en/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = kdev/docs/en

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu kdev/docs/en/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-data-local
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-local
uninstall: uninstall-am
all-am: Makefile
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_STRIP_FLAG=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-local install-data-am install-data install-am install \
uninstall-local uninstall-am uninstall all-redirect all-am all \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


install-data-local:
#>- 	$(mkinstalldirs) $(prefix)/doc/kdev/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(prefix)/doc/kdev/
#>- 	$(INSTALL_DATA) index.html $(prefix)/doc/kdev/index.html
#>+ 1
	$(INSTALL_DATA) index.html $(DESTDIR)$(prefix)/doc/kdev/index.html
#>- 	$(mkinstalldirs) $(prefix)/doc/kdev/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(prefix)/doc/kdev/
#>- 	$(INSTALL_DATA) index-1.html $(prefix)/doc/kdev/index-1.html
#>+ 1
	$(INSTALL_DATA) index-1.html $(DESTDIR)$(prefix)/doc/kdev/index-1.html
#>- 	$(mkinstalldirs) $(prefix)/doc/kdev/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(prefix)/doc/kdev/
#>- 	$(INSTALL_DATA) index-2.html $(prefix)/doc/kdev/index-2.html
#>+ 1
	$(INSTALL_DATA) index-2.html $(DESTDIR)$(prefix)/doc/kdev/index-2.html
#>- 	$(mkinstalldirs) $(prefix)/doc/kdev/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(prefix)/doc/kdev/
#>- 	$(INSTALL_DATA) index-3.html $(prefix)/doc/kdev/index-3.html
#>+ 1
	$(INSTALL_DATA) index-3.html $(DESTDIR)$(prefix)/doc/kdev/index-3.html
#>- 	$(mkinstalldirs) $(prefix)/doc/kdev/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(prefix)/doc/kdev/
#>- 	$(INSTALL_DATA) index-4.html $(prefix)/doc/kdev/index-4.html
#>+ 1
	$(INSTALL_DATA) index-4.html $(DESTDIR)$(prefix)/doc/kdev/index-4.html
#>- 	$(mkinstalldirs) $(prefix)/doc/kdev/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(prefix)/doc/kdev/
#>- 	$(INSTALL_DATA) index-5.html $(prefix)/doc/kdev/index-5.html
#>+ 1
	$(INSTALL_DATA) index-5.html $(DESTDIR)$(prefix)/doc/kdev/index-5.html
#>- 	$(mkinstalldirs) $(prefix)/doc/kdev/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(prefix)/doc/kdev/
#>- 	$(INSTALL_DATA) index-6.html $(prefix)/doc/kdev/index-6.html
#>+ 1
	$(INSTALL_DATA) index-6.html $(DESTDIR)$(prefix)/doc/kdev/index-6.html

uninstall-local:
#>- 	-rm -f $(prefix)/doc/kdev/index.html
#>+ 1
	-rm -f $(DESTDIR)$(prefix)/doc/kdev/index.html
#>- 	-rm -f $(prefix)/doc/kdev/index-1.html
#>+ 1
	-rm -f $(DESTDIR)$(prefix)/doc/kdev/index-1.html
#>- 	-rm -f $(prefix)/doc/kdev/index-2.html
#>+ 1
	-rm -f $(DESTDIR)$(prefix)/doc/kdev/index-2.html
#>- 	-rm -f $(prefix)/doc/kdev/index-3.html
#>+ 1
	-rm -f $(DESTDIR)$(prefix)/doc/kdev/index-3.html
#>- 	-rm -f $(prefix)/doc/kdev/index-4.html
#>+ 1
	-rm -f $(DESTDIR)$(prefix)/doc/kdev/index-4.html
#>- 	-rm -f $(prefix)/doc/kdev/index-5.html
#>+ 1
	-rm -f $(DESTDIR)$(prefix)/doc/kdev/index-5.html
#>- 	-rm -f $(prefix)/doc/kdev/index-6.html
#>+ 1
	-rm -f $(DESTDIR)$(prefix)/doc/kdev/index-6.html

####### kdevelop will overwrite this part!!! (end)############

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 2
docs: docs-am

#>+ 2
docs-am:

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu kdev/docs/en/Makefile
	cd $(top_srcdir) && perl am_edit kdev/docs/en/Makefile.in


#>+ 2
final:
	$(MAKE) all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
