package com.redsaga.hibnatesample.step2.dao;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public abstract class _RootDAO extends com.redsaga.hibnatesample.step2.base._BaseRootDAO {
}