package com.redsaga.hibnatesample.step2.dao;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 */
public  class RootDAO extends com.redsaga.hibnatesample.step2.base._BaseRootDAO {
	public static RootDAO instance;

	public static RootDAO getInstance () {
		if (null == instance) instance = new RootDAO();
		return instance;
	}

	protected Class getReferenceClass() {
		return null;
	}
}
