CREATE TABLE PRODUCTS (
          ID INTEGER NOT NULL PRIMARY KEY,
          DESCRIPTION VARCHAR(255),
          PRICE DECIMAL(15,2)
        );

INSERT INTO PRODUCTS (ID, DESCRIPTION, PRICE) VALUES(1, 'Lamp', 5.78);
INSERT INTO PRODUCTS (ID, DESCRIPTION, PRICE) VALUES(2, 'Table', 75.29);
INSERT INTO PRODUCTS (ID, DESCRIPTION, PRICE) VALUES(3, 'Chair', 22.81);
