package com.redsaga.hibnatesample.step1.synchronizer.dao;

import com.redsaga.hibnatesample.step1.synchronizer.base.BaseArticleDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the article table.
 * Any customizations belong here.
 */
public class ArticleDAO extends BaseArticleDAO {
}