/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Mar 24 11:07:44 GMT+08:00 2006 by MyEclipse Hibernate Tool.
 */
package com.taifook.adminportal.model;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

/**
 * A class that represents a row in the CS_BROADCAST table. You can customize
 * the behavior of this class by editing the class, {@link CsBroadcast()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCsBroadcast implements Serializable {
	/**
	 * The cached hash code value for this instance. Settting to 0 triggers
	 * re-calculation.
	 */
	private int hashValue = 0;

	/** The composite primary key value. */
	private java.lang.Long seqno;

	/** The value of the simple starttime property. */
	private java.util.Date starttime;

	/** The value of the simple endtime property. */
	private java.util.Date endtime;

	/** The value of the simple broadcastLevel property. */
	private java.lang.String broadcastLevel;

	/** The value of the simple type property. */
	private java.lang.String contentType;

	private java.lang.String channels;

	/** The value of the simple contentEnUs property. */
	private java.lang.String contentEnUs;

	/** The value of the simple contentZhCn property. */
	private java.lang.String contentZhCn;

	/** The value of the simple contentZhTw property. */
	private java.lang.String contentZhTw;

	private java.util.Date lastupdatetime;

	/**
	 * Simple constructor of AbstractCsBroadcast instances.
	 */
	public AbstractCsBroadcast() {
	}

	/**
	 * Constructor of AbstractCsBroadcast instances given a simple primary key.
	 * 
	 * @param seqno
	 */
	public AbstractCsBroadcast(java.lang.Long seqno) {
		this.setSeqno(seqno);
	}

	/**
	 * Return the simple primary key value that identifies this object.
	 * 
	 * @return java.lang.Long
	 */
	public java.lang.Long getSeqno() {
		return seqno;
	}

	/**
	 * Set the simple primary key value that identifies this object.
	 * 
	 * @param seqno
	 */
	public void setSeqno(java.lang.Long seqno) {
		this.hashValue = 0;
		this.seqno = seqno;
	}

	/**
	 * Return the value of the STARTTIME column.
	 * 
	 * @return java.util.Date
	 */
	public java.util.Date getStarttime() {
		return this.starttime;
	}

	/**
	 * Set the value of the STARTTIME column.
	 * 
	 * @param starttime
	 */
	public void setStarttime(java.util.Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * Return the value of the ENDTIME column.
	 * 
	 * @return java.util.Date
	 */
	public java.util.Date getEndtime() {
		return this.endtime;
	}

	/**
	 * Set the value of the ENDTIME column.
	 * 
	 * @param endtime
	 */
	public void setEndtime(java.util.Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * Return the value of the BROADCAST_LEVEL column.
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBroadcastLevel() {
		return this.broadcastLevel;
	}

	/**
	 * Set the value of the BROADCAST_LEVEL column.
	 * 
	 * @param broadcastLevel
	 */
	public void setBroadcastLevel(java.lang.String broadcastLevel) {
		this.broadcastLevel = broadcastLevel;
	}

	/**
	 * Return the value of the TYPE column.
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getContentType() {
		return this.contentType;
	}

	/**
	 * Set the value of the TYPE column.
	 * 
	 * @param type
	 */
	public void setContentType(java.lang.String contentType) {
		this.contentType = contentType;
	}

	/**
	 * Return the value of the CONTENT_EN_US column.
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getContentEnUs() {
		return this.contentEnUs;
	}

	/**
	 * Set the value of the CONTENT_EN_US column.
	 * 
	 * @param contentEnUs
	 */
	public void setContentEnUs(java.lang.String contentEnUs) {
			this.contentEnUs = contentEnUs;
	}

	/**
	 * Return the value of the CONTENT_ZH_CN column.
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getContentZhCn() {
		return this.contentZhCn;
	}

	/**
	 * Set the value of the CONTENT_ZH_CN column.
	 * 
	 * @param contentZhCn
	 */
	public void setContentZhCn(java.lang.String contentZhCn) {
			this.contentZhCn = contentZhCn;
	}

	/**
	 * Return the value of the CONTENT_ZH_TW column.
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getContentZhTw() {
		return this.contentZhTw;
	}

	/**
	 * Set the value of the CONTENT_ZH_TW column.
	 * 
	 * @param contentZhTw
	 */
	public void setContentZhTw(java.lang.String contentZhTw) {
			this.contentZhTw = contentZhTw;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the
	 * primary key values.
	 * 
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof CsBroadcast))
			return false;
		CsBroadcast that = (CsBroadcast) rhs;
		if (this.getSeqno() == null || that.getSeqno() == null)
			return false;
		return (this.getSeqno().equals(that.getSeqno()));
	}

	/**
	 * Implementation of the hashCode method conforming to the Bloch pattern
	 * with the exception of array properties (these are very unlikely primary
	 * key types).
	 * 
	 * @return int
	 */
	public int hashCode() {
		if (this.hashValue == 0) {
			int result = 17;
			int seqnoValue = this.getSeqno() == null ? 0 : this.getSeqno()
					.hashCode();
			result = result * 37 + seqnoValue;
			this.hashValue = result;
		}
		return this.hashValue;
	}

	public java.lang.String getChannels() {
		return channels;
	}

	public void setChannels(java.lang.String channels) {
		this.channels = channels;
	}

	public java.util.Date getLastupdatetime() {
		return lastupdatetime;
	}

	public void setLastupdatetime(java.util.Date lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}
}
