/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Mar 31 16:01:01 GMT+08:00 2006 by MyEclipse Hibernate Tool.
 */
package com.taifook.adminportal.model;

import java.io.Serializable;

/**
 * A class that represents a row in the CS_SERVICEMONITOR table. You can
 * customize the behavior of this class by editing the class,
 * {@link CsServicemonitor()}. WARNING: DO NOT EDIT THIS FILE. This is a
 * generated file that is synchronized by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCsServicemonitor implements Serializable {
	/**
	 * The cached hash code value for this instance. Settting to 0 triggers
	 * re-calculation.
	 */
	private int hashValue = 0;

	/** The composite primary key value. */
	private java.lang.Long seqno;

	/** The value of the simple servicename property. */
	private java.lang.String servicename;

	/** The value of the simple status property. */
	private java.lang.String status;

	/** The value of the simple actionId property. */
	private java.lang.String actionId;

	/** The value of the simple ip property. */
	private java.lang.String ip;

	/** The value of the simple accesstime property. */
	private java.util.Date accesstime;

	/** The value of the simple expend property. */
	private java.lang.Long expendtime;

	/**
	 * Simple constructor of AbstractCsServicemonitor instances.
	 */
	public AbstractCsServicemonitor() {
	}

	/**
	 * Constructor of AbstractCsServicemonitor instances given a simple primary
	 * key.
	 * 
	 * @param seqno
	 */
	public AbstractCsServicemonitor(java.lang.Long seqno) {
		this.setSeqno(seqno);
	}

	/**
	 * Return the simple primary key value that identifies this object.
	 * 
	 * @return java.lang.Long
	 */
	public java.lang.Long getSeqno() {
		return seqno;
	}

	/**
	 * Set the simple primary key value that identifies this object.
	 * 
	 * @param seqno
	 */
	public void setSeqno(java.lang.Long seqno) {
		this.hashValue = 0;
		this.seqno = seqno;
	}

	/**
	 * Return the value of the SERVICENAME column.
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getServicename() {
		return this.servicename;
	}

	/**
	 * Set the value of the SERVICENAME column.
	 * 
	 * @param servicename
	 */
	public void setServicename(java.lang.String servicename) {
		this.servicename = servicename;
	}

	/**
	 * Return the value of the STATUS column.
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getStatus() {
		return this.status;
	}

	/**
	 * Set the value of the STATUS column.
	 * 
	 * @param status
	 */
	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	/**
	 * Return the value of the STATUS column.
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getActionId() {
		return this.actionId;
	}

	/**
	 * Set the value of the STATUS column.
	 * 
	 * @param status
	 */
	public void setActionId(java.lang.String actionId) {
		this.actionId = actionId;
	}

	/**
	 * Return the value of the IP column.
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getIp() {
		return this.ip;
	}

	/**
	 * Set the value of the IP column.
	 * 
	 * @param ip
	 */
	public void setIp(java.lang.String ip) {
		this.ip = ip;
	}

	/**
	 * Return the value of the ACCESSTIME column.
	 * 
	 * @return java.util.Date
	 */
	public java.util.Date getAccesstime() {
		return this.accesstime;
	}

	/**
	 * Set the value of the ACCESSTIME column.
	 * 
	 * @param accesstime
	 */
	public void setAccesstime(java.util.Date accesstime) {
		this.accesstime = accesstime;
	}

	/**
	 * Return the value of the ACCESSTIME column.
	 * 
	 * @return java.util.Date
	 */
	public java.lang.Long getExpendtime() {
		return this.expendtime;
	}

	/**
	 * Set the value of the ACCESSTIME column.
	 * 
	 * @param accesstime
	 */
	public void setExpendtime(long expendtime) {
		this.expendtime = new Long(expendtime);
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the
	 * primary key values.
	 * 
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		if (rhs == null)
			return false;
		if (!(rhs instanceof CsServicemonitor))
			return false;
		CsServicemonitor that = (CsServicemonitor) rhs;
		if (this.getSeqno() == null || that.getSeqno() == null)
			return false;
		return (this.getSeqno().equals(that.getSeqno()));
	}

	/**
	 * Implementation of the hashCode method conforming to the Bloch pattern
	 * with the exception of array properties (these are very unlikely primary
	 * key types).
	 * 
	 * @return int
	 */
	public int hashCode() {
		if (this.hashValue == 0) {
			int result = 17;
			int seqnoValue = this.getSeqno() == null ? 0 : this.getSeqno()
					.hashCode();
			result = result * 37 + seqnoValue;
			this.hashValue = result;
		}
		return this.hashValue;
	}
}
