/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Mar 30 14:48:38 GMT+08:00 2006 by MyEclipse Hibernate Tool.
 */
package com.taifook.adminportal.model;

import java.io.Serializable;

/**
 * A class that represents a row in the CS_ONLINEUSER table. 
 * You can customize the behavior of this class by editing the class, {@link CsOnlineuser()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCsOnlineuser 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The simple primary key value. */
    private CsOnlineuserKey id;

    /** The value of the simple sessionid property. */
    private java.lang.String sessionid;

    /** The value of the simple logintime property. */
    private java.util.Date logintime;

    /**
     * Simple constructor of AbstractCsOnlineuser instances.
     */
    public AbstractCsOnlineuser()
    {
    }

    /**
     * Constructor of AbstractCsOnlineuser instances given a composite primary key.
     * @param id
     */
    public AbstractCsOnlineuser(CsOnlineuserKey id)
    {
        this.setId(id);
    }

    /**
     * Return the composite id instance that identifies this object.
     * @return CsOnlineuserKey
     */
    public CsOnlineuserKey getId()
    {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * @param id
     */
    public void setId(CsOnlineuserKey id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the SESSIONID column.
     * @return java.lang.String
     */
    public java.lang.String getSessionid()
    {
        return this.sessionid;
    }

    /**
     * Set the value of the SESSIONID column.
     * @param sessionid
     */
    public void setSessionid(java.lang.String sessionid)
    {
        this.sessionid = sessionid;
    }

    /**
     * Return the value of the LOGINTIME column.
     * @return java.util.Date
     */
    public java.util.Date getLogintime()
    {
        return this.logintime;
    }

    /**
     * Set the value of the LOGINTIME column.
     * @param logintime
     */
    public void setLogintime(java.util.Date logintime)
    {
        this.logintime = logintime;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CsOnlineuser))
            return false;
        CsOnlineuser that = (CsOnlineuser) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            if (this.getId() == null)
            {
                result = super.hashCode();
            }
            else
            {
                result = this.getId().hashCode();
            }
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
