/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Mar 30 14:48:38 GMT+08:00 2006 by MyEclipse Hibernate Tool.
 */
package com.taifook.adminportal.model;

import java.io.Serializable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * A class representing a composite primary key id for the CS_ONLINEUSER
 * table.  This object should only be instantiated for use with instances 
 * of the CsOnlineuser class.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized 
 * by MyEclipse Hibernate tool integration.
 */
public class CsOnlineuserKey implements Serializable {
	private static final long serialVersionUID = 1L;

	/** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
	private volatile int hashValue = 0;

	/** The value of the CHANNELCODE component of this composite id. */
	private java.lang.String channelcode;

	/** The value of the USERID component of this composite id. */
	private java.lang.String userid;

	/**
	 * Simple constructor of CsOnlineuserKey instances.
	 */
	public CsOnlineuserKey() {
	}

	/**
	 * Returns the value of the channelcode property.
	 * @return java.lang.String
	 */
	public java.lang.String getChannelcode() {
		return channelcode;
	}

	/**
	 * Sets the value of the channelcode property.
	 * @param channelcode
	 */
	public void setChannelcode(java.lang.String channelcode) {
		hashValue = 0;
		this.channelcode = channelcode;
	}

	/**
	 * Returns the value of the userid property.
	 * @return java.lang.String
	 */
	public java.lang.String getUserid() {
		return userid;
	}

	/**
	 * Sets the value of the userid property.
	 * @param userid
	 */
	public void setUserid(java.lang.String userid) {
		hashValue = 0;
		this.userid = userid;
	}

	/**
	 * Implementation of the equals comparison on the basis of equality of the id components.
	 * @param rhs
	 * @return boolean
	 */
	public boolean equals(Object rhs) {
		/*        if (rhs == null)
		 return false;
		 if (! (rhs instanceof CsOnlineuserKey))
		 return false;
		 CsOnlineuserKey that = (CsOnlineuserKey) rhs;
		 if (this.getChannelcode() == null || that.getChannelcode() == null)
		 {
		 return false;
		 }
		 if (! this.getChannelcode().equals(that.getChannelcode()))
		 {
		 return false;
		 }
		 if (this.getUserid() == null || that.getUserid() == null)
		 {
		 return false;
		 }
		 if (! this.getUserid().equals(that.getUserid()))
		 {
		 return false;
		 }*/

		if (rhs == this) {
			return true;
		}

		if (!(rhs instanceof CsOnlineuserKey)) {
			return false;
		}

		CsOnlineuserKey pk = (CsOnlineuserKey) rhs;

		return new EqualsBuilder()
					.appendSuper(super.equals(rhs))
					.append(this.channelcode, pk.getChannelcode())
					.append(this.userid, pk.getUserid())
					.isEquals();
	}

	/**
	 * Implementation of the hashCode method conforming to the Bloch pattern with
	 * the exception of array properties (these are very unlikely primary key types).
	 * @return int
	 */
	public int hashCode() {
		/*		if (this.hashValue == 0) {
		 int result = 17;
		 int channelcodeValue = this.getChannelcode() == null ? 0 : this.getChannelcode().hashCode();
		 result = result * 37 + channelcodeValue;
		 int useridValue = this.getUserid() == null ? 0 : this.getUserid().hashCode();
		 result = result * 37 + useridValue;
		 this.hashValue = result;
		 }*/
		this.hashValue = new HashCodeBuilder(17, 37)
			.appendSuper(super.hashCode())
			.append(this.channelcode)
			.append(this.userid)
			.toHashCode();
		
		return this.hashValue;
	}
}
