/* Generated by Together */

package com.itsz.sht.common;

import java.util.ArrayList;

public class NotificationConstants {
    public static final String NOTIFY_ID = "NOTIFY_ID";//Sequence Key.
    public static class PRODUCT_ID{
	    	public static final String NOTIFY_SMS = "NOTIFY_SMS",
	    							   NOTIFY_EML = "NOITFY_EMAIL",
	    							   NOTIFY_FAX = "NOTIFY_FAX";
    }

	/* from eService4 -- commented by xryang --Nov 29, 2005*/
    public static class DB{
//        public static final byte
//            OPERAND_GREATER_THAN_AND_EQUAL = TriggerServerConstant.GREATER_THAN_AND_EQUAL,
//            OPERAND_LESS_THAN_AND_EQUAL = TriggerServerConstant.LESS_THAN_AND_EQUAL ;
//            OPERAND_NOT_EQUAL = 9;
//        public static final int
//            TRI_CONDITION_GREATER_THAN_AND_EQUAL = TriggerServerConstant.GREATER_THAN_AND_EQUAL,
//            TRI_CONDITION_LESS_THAN_AND_EQUAL = TriggerServerConstant.LESS_THAN_AND_EQUAL ;
//        public static final int
//            TRI_TYPE_NORMPRC = Constants.COMPARE_TYPE_NOMINALPRICE ,
//            TRI_TYPE_PERCENTCHG = Constants.COMPARE_TYPE_PERCENTCHANGE ,
//            TRI_TYPE_VOLUME = Constants.COMPARE_TYPE_VOLUME ;
//        public static final String
//            TRI_STATUS_SEND = Constants.T_STATUS_SEND ,
//            TRI_STATUS_SUBSCRIBE = Constants.T_STATUS_SUBSCRIBE ,
//            TRI_STATUS_UNSUBSCRIBE = Constants.T_STATUS_UNSUBSCRIBE ;
//        public static final String EXCHANGE_HK = "HKEX";
//        public static final String
//            PRODUCT_SECURITIES = "SEC",
//            PRODUCT_FUTURES = "FUT",
//            PRODUCT_INDEX = "IDX";
//        public static final String
//            PRODUCT_PREFIX_SECURITIES = "110:",
//            PRODUCT_PREFIX_FUTURES = "510:";
//        public static final String
//            ALERT_STATUS_I18N_PREFIX="pricealert_entry_status_",
//            ALERT_STATUS_MONITORING = "Monitoring",
//            ALERT_STATUS_FAIL = "Fail",
//            ALERT_STATUS_INSUFFICIENT_AU = "ConsumeAccessFail",
//            ALERT_STATUS_ALERTED = "Alerted",
//            ALERT_STATUS_EXPIRED = "Expired",
//            ALERT_STATUS_USRPACK_EXPIRED ="UserPackExpr";
        public static final String
            LOG_ACTION_ADD = "ADD",
            LOG_ACTION_EDIT = "EDIT",
            LOG_ACTION_DEL = "DEL";
        public static final String
            NOTIFICATION_CNNL_SMS = "SMS",
            NOTIFICATION_CNNL_EMAIL="EMAIL",
            NOTIFICATION_CNNL_WEB = "WEB",
        	NOTIFICATION_CNNL_FAX = "FAX",
        	NOTIFICATION_NO_CNNL  = "NO_CHANNEL";
        public static final String
        	NOTIFICATION_TYPE_COM = "COM",
        	NOTIFICATION_TYPE_NEWS = "NEWS",
        	NOTIFICATION_TYPE_PALRT = "PALRT",
        	NOTIFICATION_TYPE_OTCON = "OTCON",
        	NOTIFICATION_TYPE_PROM = "PROM",
        	NOTIFICATION_TYPE_ACCI = "ACCI",
        	NOTIFICATION_TYPE_IPO = "IPO",
        	NOTIFICATION_TYPE_PLACE = "PLACE";
        public static final String
        	NOTIFICATION_ORDER_TYPE_INPUT_RECEIVE = "INPUT_RECEIVE",
        	NOTIFICATION_ORDER_TYPE_INPUT_REJECT = "INPUT_REJECT",
        	NOTIFICATION_ORDER_TYPE_AMEND_RECEIVE = "AMEND_RECEIVE",
        	NOTIFICATION_ORDER_TYPE_AMEND_REJECT = "AMEND_REJECT",
        	NOTIFICATION_ORDER_TYPE_CANCEL_RECEIVE = "CANCEL_RECEIVE",
        	NOTIFICATION_ORDER_TYPE_CANCEL_REJECT = "CANCEL_REJECT",
        	NOTIFICATION_ORDER_TYPE_CANCEL_FULL = "CANCEL_FULL",
        	NOTIFICATION_ORDER_TYPE_COMPLETED = "COMPLETED";
//        public static final String
//            NOTIFICATION_LOG_STATUS_INVALID = "Invalid",
//            NOTIFICATION_LOG_STATUS_SUCCESS = "Success",
//            NOTIFICATION_LOG_STATUS_SENDFAIL = "Send SMS Fail",
//            NOTIFICATION_LOG_STATUS_CONSUMEFAIL = "Add Consumed Fail";
//        public static final String
//            NOTIFICATION_GATEWAY_AIRWAP = "Airwap",
//            NOTIFICATION_GATEWAY_ORANGE = "Orange";
    }

    public static final ArrayList allNotifyCat;
    static{
    	allNotifyCat = new ArrayList();
    	allNotifyCat.add(DB.NOTIFICATION_ORDER_TYPE_INPUT_RECEIVE);
    	allNotifyCat.add(DB.NOTIFICATION_ORDER_TYPE_INPUT_REJECT);
    	allNotifyCat.add(DB.NOTIFICATION_ORDER_TYPE_AMEND_RECEIVE);
    	allNotifyCat.add(DB.NOTIFICATION_ORDER_TYPE_AMEND_REJECT);
    	allNotifyCat.add(DB.NOTIFICATION_ORDER_TYPE_CANCEL_RECEIVE);
    	allNotifyCat.add(DB.NOTIFICATION_ORDER_TYPE_CANCEL_REJECT);
    	allNotifyCat.add(DB.NOTIFICATION_ORDER_TYPE_CANCEL_FULL);
    	allNotifyCat.add(DB.NOTIFICATION_ORDER_TYPE_COMPLETED);
    };
    public static final String
	    JNDI_REMOTE_NOTIFICATION_MANAGE = "ejb/NotificationServerManage",
	    JNDI_LOCAL_NOTIFICATION_MANAGE = "local/NotificationServerManage";
//        JNDI_REMOTE_PRCALERT_MANAGE = "ejb/PriceAlertManage",
//        JNDI_LOCAL_PRCALERT_MANGE = "local/PriceAlertManage",
//        JNDI_REMOTE_PRCALERT_REPORT = "ejb/PriceAlertReport",
//        JNDI_LOCAL_PRCALERT_REPORT = "local/PriceAlertReport",
//        JNDI_REMOTE_TRIGGERINFO_MANAGE = "ejb/TriggerInfoManage",
//        JNDI_LOCAL_TRIGGERINFO_MANAGE = "local/TriggerInfoManage";
//    public static class Biz{
//        public static final String
//            ALERT_ENTRY_STATUS_UNSEND="pricealert_unsend",
//            ALERT_ENTRY_STATUS_SENDED="pricealert_send",
//            ALERT_ENTRY_STATUS_PARTIALSEND="pricealert_partialsend",
//            ALERT_ENTRY_STATUS_EXPIRED="pricealert_expired";
//        public static final String
//            UPPER_LIMIT="UPPER_LIMIT",
//            LOWER_LIMIT="LOWER_LIMIT",
//            UP_PERCENT_MORETHAN="UP_PCNT_MORETHAN",
//            DOWN_PERCENT_MORETHAN="DOWN_PCNT_MORETHAN",
//            VOLUME_MORETHAN="VOLUME_MORETHAN",
//            UPPER_LIMIT_I18NKEY="formdata_pricealert-alerttype_UPPER_LIMIT",
//            LOWER_LIMIT_I18NKEY="formdata_pricealert-alerttype_LOWER_LIMIT",
//            UP_PERCENT_MORETHAN_I18NKEY="formdata_pricealert-alerttype_UP_PCNT_MORETHAN",
//            DOWN_PERCENT_MORETHAN_I18NKEY="formdata_pricealert-alerttype_DOWN_PCNT_MORETHAN",
//            VOLUME_MORETHAN_I18NKEY="formdata_pricealert-alerttype_VOLUME_MORETHAN";
//    }

//    public static final String MDB_ACT_USER = "Price alert MDB";
//    public static final String TRIGGER_ID_SPLITTER = "|";
//
//    public static class WEB {
//        public static final String
//            SVC_PACKAGE_LIST = "service_package_list",
//            ALERT_ENTRIES = "alert_entries",
//            SMS_REGION = "sms_region",
//            MOBILE_PROVIDER_LIST = "mobile_provider_list",
//            MOBILE_NO = "mobile_no",
//            MOBILE_PROVIDER = "mobile_provider",
//            MOBILE_COUNTRY_CODE = "mobile_country_code",
//            MOBILE_COUNTRY_LIST = "mobile_country_list",
//            EMAIL_ADDR = "email_addr",
//            USER_PROFILE = "userProfileDto",
//            PUCH_PACK_FORM = "purchase_package_form" ,
//            TRIGGER_STATUS = "trigger_status";
//        public static int
//            SPARE_MAX_ENTRIES = 10 ,
//            SPARE_RTQ_REFRESH = 10 ;
//        public static String
//            ALL_AU = "all_au",
//            REMAINED_AU = "remained_au",
//            LOCKED_AU = "locked_au";
//
//        public static String
//            ACTION_ADD_ENTRY = "ADD_ENTRY" ,
//            ACTION_CHG_ENTRY = "CHG_ENTRY" ,
//            ACTION_DEL_ENTRY = "DEL_ENTRY" ,
//            ACTION_ADD_INFO = "ADD_INFO" ,
//            ACTION_CHG_INFO = "CHG_INFO" ,
//            ACTION_DEL_INFO = "DEL_INFO" ;
//        public static String TRIGGER_AVAILABLE = "A";
//        public static String TRIGGER_UNAVAILABLE = "I";


//    }
}
